### ISSUE TITLE
Extra monsters in remove non player form

### ISSUE THREAD

**Issue by Mazzmnza42** [artg3-dev/DM_Tools#47]
**Describe the bug**
Adding multiple monsters of the same type won't add additional monsters (as intended I imagine) but it will add additional monsters to the "remove" list.

**To Reproduce**
1. Go to **Create New Encounter** 
2. Click **"+"** and create a monster
3. Select the monster you just created from the **Create Monster** drop-down menu 
4. Click **"+"** ...No new monster is added to the **Non Players** list
5. Click **"-"** ...Note there are two entries of the same monster in the **Remove Non Players Form**

**Expected behavior**
Clicking the **"+"** when an existing monster is selected either creates a new monster of the same type, or creates a message that recommends using the **Horde** feature. The amount and type of monsters in the **Non Player** list should match the the amount and type of monsters in the **Remove Non Players Form**

**Screenshots**
![Monster removal bug](https://user-images.githubusercontent.com/60635738/73711657-8ca7b180-46d5-11ea-90b9-1d0bf532de56.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Jave Runtime Environment: 1.8.0_241-b07
 - Version 8 Update 241

**Comment by artg3-dev** [comment]
I like the horde popup idea, I think I'll use something like that! 

edit: typo

**Comment by artg3-dev** [comment]
@Mazzmnza42  do you think the user should be able to name each version of a given 'Monster', or should it be an identifier behind the scenes?

**Comment by Mazzmnza42** [comment]
I think with the way you currently have it, i could create Ogre CR 5 with 60 HP and then Super Ogre CR 7 with 100HP. I guess if the identifier was visible, I could be handy. Can you give me an example of indicator behind the scenes?

**Comment by artg3-dev** [comment]
Currently implemented EntityTracker and now use it in the NonPlayerGetInitiativePanel.

**Need to fix the handling of the entities by the RemoveNonPlayerDialog.**
- Pass it the EntityTracker instead of an arraylist.
- Use uniquename instead of name.

**Comment by Mazzmnza42** [comment]
Instead of fixing RemoveNonPlayerDialog, consider Issue #59
