### ISSUE TITLE
Field for additional modifiers for skills in the PC Form

### ISSUE THREAD

**Issue by Mazzmnza42** [artg3-dev/DM_Tools#54]
**Is your feature request related to a problem? Please describe.**
The Skills section may not always reflect a PC's actual score in that skill in some specific situations. For example: Rogue's Expertise. They may be able to add double their proficiency bonus to certain skills.

**Describe the solution you'd like**
Add a field to the right of each skill in the PC form. Here, you can enter numeric modifiers to that skill.

**Describe alternatives you've considered**
Add a separate section called Skill Modifiers. This section with have 4ish rows. in each row, there will be a dropdown menu and a field. the dropdown menu will consist of all skills. once a skills is selected, you can enter a number in the field. This number will modify the selected skill.

**Comment by artg3-dev** [comment]
Can you tell me or point me to where I can read about what exactly adds additional modifiers?

**Comment by Mazzmnza42** [comment]
Various class/race features add additional modifiers. Rogue's **Expertise** and Bard's **Jack of All Trades** come to mind. I've copied the rules text for these below.

**Expertise**
At 1st Level, choose two of your skill Proficiencies, or one of your skill Proficiencies and your proficiency with Thieves' Tools. Your Proficiency Bonus is doubled for any ability check you make that uses either of the chosen Proficiencies.

At 6th level, you can choose two more of your Proficiencies (in Skills or with thieves' tools) to gain this benefit.

**Jack of All Trades**
Starting at 2nd Level, you can add half your Proficiency Bonus, rounded down, to any ability check you make that doesn't already include your Proficiency Bonus.

**Comment by artg3-dev** [comment]
Hmmmm. I think more likely than manually adding this, it will be part of the PlayableClass bard. (I call them PlayableClass becuase Java already uses the term Class and it caused confusion). Unless there are other things that would make the above messy. The user-side selection would simply be under PlayableClass: Rogue - Expertise: choose 2 skills or 1 and thieves tools, and the math part would be automatic.

**Comment by Mazzmnza42** [comment]
that's probably best. I think some feats do this too though. But you could handle them the same way you would handle the class. Should this issue be closed then?

**Comment by artg3-dev** [comment]
Yes I'd imagine it would. Any sort of calculated math will be done behind the scenes. I will only prompt for input when there is a choice to be made
